replicaCount: 3

env:
  database: "off"

ingressController:
  installCRDs: false
  enabled: false

proxy:
  # Enable creating a Kubernetes service for the proxy
  enabled: true
  type: ClusterIP
  annotations: {}

  http:
    enabled: true
    servicePort: 80
    containerPort: 8000
    parameters: []

  tls:
    # Enable HTTPS listen for the proxy
    enabled: false
  
  stream: {}

  ingress:
    # Enable/disable exposure using ingress.
    enabled: true
    hosts: ["localhost"]
    
    annotations: {}
    # Ingress path.
    path: /gw

dblessConfig:
  # Either Kong's configuration is managed from an existing ConfigMap (with Key: kong.yml)
  configMap: "kong-config"
